version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: file-server-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data



  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: file-server-admin
    depends_on:
      - api
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE=http://api:8000
    volumes:
      - ./.env:/app/.env:ro


